# strategy = "polling" ==> the data will be fetched once, at server start-up
# strategy = "webhook" ==> POST new data to /webhook
strategy = "webhook"

# Poll URL (required for polling strategy)
# url = "https://trmnl-dsn.netlify.app/dsn.json"

# Polling headers (optional, for polling strategy)
# [polling_headers]
# authorization = "bearer 123"
# content-type = "application/json"
